# Site settings
title: Hao Zhou's Homepage          # 周浩教授个人主页
header-img: "static/2024_p.jpeg"    # 显示在首页的背景图片
email: haozhou0806@gmail.com    
url: "https://zhouh.github.io"     # 个人主页地址
baseurl: ""                        # Jekyll base URL
